config/routes.rb
WineCrawl::Application.routes.draw do
  match '/search' => 'wine_monitors#search'#, defaults: {page: 1}
  authenticated :user do
    root :to => 'wine_monitors#index'
    scope module: 'user' do
      resources :wine_links
    end
  end
  resources :wine_links
  resources :user_monitors
  resources :comments, only: [:index, :show, :create]
  get '/go/:lib/:id' => 'wine_monitors#links',as: :go
  post '/go/:lib/:id' => 'wine_monitors#links',as: :go
  resources :wine_monitors, only: [:index, :show, :new, :create] do
    resources :comments, only: [:index,:create]
    get 'category/:id' => 'wine_monitors#category', on: :collection, as: 'category'
    get 'categories' => 'wine_monitors#categories', on: :collection, as: 'categories'
    #collection do
      #match :search
    #end
  end
  resources :wines, only: [:index, :show] do
    resources :comments, only: [:index,:create]
  end
  #resources :wine_price_histories
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "wine_monitors#index"

  devise_for :users, controllers: {
    omniauth_callbacks: :authentications,
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  ActiveAdmin.routes(self)
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :content, type: String
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  attr_accessible :content

  scope :recent, desc(:created_at)
  scope :system, where(commentable: nil)
  scope :with_commentable, not_in(commentable: nil)
  scope :sidebar_comments, with_commentable.recent.limit(10)

  validates :content, length: 1..300
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  before_filter :authenticate_user!, except: [:index, :show]
  respond_to :js
  belongs_to :commodity, optional: true
  belongs_to :group, optional: true
  belongs_to :article, optional: true
  actions :index, :create

  def index
    index! do
      if parent
        add_crumb(I18n.t("controller.#{parent.class.name.downcase.pluralize}"), polymorphic_path(parent.class))
        add_crumb(parent.name, polymorphic_path(parent))
      end
      add_crumb(I18n.t("controller.comments"))
    end
  end

  def create
    create! do |s,f|
      s.html{
        redirect_to parent? ? parent : system_contact_path
      }
      s.js{
        @comment.user = current_user
        @comment.save
        flash[:notice] = '提交成功'
      }
      f.js{
        flash[:error] = @comment.errors.full_messages
        render 'application/failure'
      }
    end
  end

  protected
  def collection
    @comments ||= end_of_association_chain.recent.page params[:cpage]
  end
end

app/views/comments/_all.html.erb
<% comments = parent.comments.recent.page(params[:comment_page]) %>
<h3>我也来说两句</h3>
<div><%= render "comments/form", parent: parent, comment: parent.comments.new, any_comments: comments.any? %></div>
<h3>评论</h3>
<div id="div_comments">
  <%= render 'comments/comments', comments: comments, parent: parent %>
</div>

app/views/comments/_all_in_dl.html.erb
<% comments = parent.comments.recent.page(params[:comment_page]) %>
<dt>我也来说两句</dt>
<dd><%= render "comments/form", parent: parent, comment: parent.comments.new, any_comments: comments.any? %></dd>
<dt>评论</dt>
<dd>
<div id="dd_comments">
  <%= render 'comments/comments', comments: comments, parent: parent %>
</div>
</dd>

app/views/comments/_comment.html.erb
<li id="<%= comment.id %>">
  <div class="comment">
    <div class="comment-info">
      <span class="user"><%= comment.user %></span>
      <span class="created_at"><%= comment.created_at %></span>
      <span class="action"></span>
    </div>
    <div class="comment-content">
      <%= comment.content %>
    </div>
  </div>
</li>

app/views/comments/_comments.html.erb
<ul class="unstyled ul-comments" id="comments">
  <%= render comments %>
</ul>
<div class="clearfix"></div>
<div class="pull-right">
  <% if parent %>
    <%= paginate comments,param_name: :cpage, :params => {controller: :comments, action: :index, :"#{parent.class.name.downcase}_id" => parent.id, id: nil}, remote: true %>
  <% else %>
    <%= paginate comments,param_name: :cpage %>
  <% end %>
</div>
<div class="clearfix"></div>
<% unless comments.any? %>
  <div id="no_comment">
    暂时还没评论，还不快来抢沙发。
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="wall_post row-fluid">
  <% if current_user %>
    <%= simple_form_for([parent,comment], remote: true) do |f| %>
      <%= f.input_field :content, as: :text, rows: 6, cols: 60, maxlength: 300, class: 'row-fluid' %>

      <%= f.button :submit, '发表评论', class: 'btn-primary ml10' %>
    <% end %>

  <% else %>
    <%= render "application/login", warn: '留言' %>
  <% end %>
</div>

app/views/comments/_hide.html.erb
<li id="<%= comment.id %>" style="display:none">
  <div class="comment">
    <div class="comment-info">
      <span class="user"><%= comment.user %></span>
      <span class="created_at"><%= comment.created_at %></span>
      <span class="action"></span>
    </div>
    <div class="comment-content">
      <%= comment.content %>
    </div>
  </div>
</li>

app/views/comments/create.js.erb
$('#no_comment').remove();
$('<%= j render 'comments/hide', comment: @comment %>').prependTo('ul#comments').fadeIn('slow');
$('#comment_content').val('');

app/views/comments/index.html.erb
<h1>
  <%= title "#{parent.to_s}的评论 第#{params[:cpage] || 1}页" %>
</h1>
<div id="div_comments">
  <%= render "comments", comments: @comments, parent: nil %>
</div>

app/views/comments/index.js.erb
$('#div_comments').html('<%= j render('comments/comments', comments: @comments, parent: parent) %>');

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>