config/routes.rb
WineCrawl::Application.routes.draw do
  match '/search' => 'wine_monitors#search'#, defaults: {page: 1}
  authenticated :user do
    root :to => 'wine_monitors#index'
    scope module: 'user' do
      resources :wine_links
    end
  end
  resources :wine_links
  resources :user_monitors
  resources :comments, only: [:index, :show, :create]
  get '/go/:lib/:id' => 'wine_monitors#links',as: :go
  post '/go/:lib/:id' => 'wine_monitors#links',as: :go
  resources :wine_monitors, only: [:index, :show, :new, :create] do
    resources :comments, only: [:index,:create]
    get 'category/:id' => 'wine_monitors#category', on: :collection, as: 'category'
    get 'categories' => 'wine_monitors#categories', on: :collection, as: 'categories'
    #collection do
      #match :search
    #end
  end
  resources :wines, only: [:index, :show] do
    resources :comments, only: [:index,:create]
  end
  #resources :wine_price_histories
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "wine_monitors#index"

  devise_for :users, controllers: {
    omniauth_callbacks: :authentications,
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  ActiveAdmin.routes(self)
end

app/models/wine_link.rb
class WineLink
  include Mongoid::Document
  include Mongoid::Timestamps
  field :url, type: String
  field :warn_price, type: Money
  field :deal_at, type: DateTime
  belongs_to :user
  belongs_to :wine_monitor

  validates :url, presence: true, format: {with: /^https?:\/\/.*/i }, uniqueness: true
  scope :undeal, where(deal_at: nil)

  after_create :test_deal
  def test_deal
    YAML.load(ENV['CRAWLS']).each do |site|
      site_klass = site.constantize.new({})
      if site_klass.is?(url)
        site_klass.url = url
        self.wine_monitor = WineMonitor.where(sn: site_klass.get_id, website: Website.where(lib: site).first).first_or_create(user: user)
        save! if changed?
        if warn_price and warn_price != 0
          user.user_monitors.create warn_price: warn_price, wine_monitor: wine_monitor
        end
        deal
        return
      end
    end
  end

  def deal
    update_attribute :deal_at, Time.now
  end
end

app/controllers/user/wine_links_controller.rb
class User::WineLinksController < InheritedResources::Base
  actions :new, :create
  def create
    create! do |success, failure|
      success.html{
        if @wine_link.wine_monitor
          redirect_to @wine_link.wine_monitor
        else
          render :create
        end
      }
    end
  end

  protected
  def begin_of_association_chain
    current_user
  end
end

app/controllers/wine_links_controller.rb
class WineLinksController < InheritedResources::Base
  actions :new, :create
  def create
    create! do |success, failure|
      success.html{
        if @wine_link.wine_monitor
          redirect_to @wine_link.wine_monitor
        else
          render :create
        end
      }
    end
  end
end

app/helpers/user/wine_links_helper.rb
module User::WineLinksHelper
end

app/helpers/wine_links_helper.rb
module WineLinksHelper
end

app/views/wine_links/_form.html.erb
<%= simple_form_for(@wine_link) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/wine_links/create.html.erb
<h1>提交成功</h1>
<p> 您所提交的网站我们暂时还不支持，但是我们会在第一时间进行处理。尽早给您带来最全面，最详尽的酒价信息。 </p>
<p> 
  <%= link_to '继续提交', new_wine_link_path, class: 'btn btn-primary' %>  
  <%= link_to '回到主页', root_path, class: 'btn btn-primary' %>  
</p>

app/views/wine_links/edit.html.erb
<h1>Editing wine_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @wine_link %> |
<%= link_to 'Back', wine_links_path %>

app/views/wine_links/index.html.erb
<h1>Listing wine_links</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wine_links.each do |wine_link| %>
  <tr>
    <td><%= wine_link.url %></td>
    <td><%= link_to 'Show', wine_link %></td>
    <td><%= link_to 'Edit', edit_wine_link_path(wine_link) %></td>
    <td><%= link_to 'Destroy', wine_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wine link', new_wine_link_path %>

app/views/wine_links/new.html.erb
<h1><%= title t("action.#{controller_name}.#{action_name}") %></h1>
<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to '简单模式', '#' %>
  </li>
  <li>
    <%= link_to '专家模式', new_wine_monitor_path %>
  </li>
</ul>

<%= render 'form' %>

<%= render "application/login", warn: '设置邮件提醒' %>

app/views/wine_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @wine_link.url %>
</p>


<%= link_to 'Edit', edit_wine_link_path(@wine_link) %> |
<%= link_to 'Back', wine_links_path %>