config/routes.rb
WineCrawl::Application.routes.draw do
  match '/search' => 'wine_monitors#search'#, defaults: {page: 1}
  authenticated :user do
    root :to => 'wine_monitors#index'
    scope module: 'user' do
      resources :wine_links
    end
  end
  resources :wine_links
  resources :user_monitors
  resources :comments, only: [:index, :show, :create]
  get '/go/:lib/:id' => 'wine_monitors#links',as: :go
  post '/go/:lib/:id' => 'wine_monitors#links',as: :go
  resources :wine_monitors, only: [:index, :show, :new, :create] do
    resources :comments, only: [:index,:create]
    get 'category/:id' => 'wine_monitors#category', on: :collection, as: 'category'
    get 'categories' => 'wine_monitors#categories', on: :collection, as: 'categories'
    #collection do
      #match :search
    #end
  end
  resources :wines, only: [:index, :show] do
    resources :comments, only: [:index,:create]
  end
  #resources :wine_price_histories
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "wine_monitors#index"

  devise_for :users, controllers: {
    omniauth_callbacks: :authentications,
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  ActiveAdmin.routes(self)
end

app/models/wine_monitor.rb
class WineMonitor
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::TaggableOn
  include Sunspot::Mongoid2
  field :lib, type: String
  field :sn, type: String
  field :min_price, type: Money
  field :current_price, type: Money
  field :price_per_liter, type: Money
  field :min_price_per_liter, type: Money
  field :name, type: String
  field :en_name, type: String
  field :description, type: String
  field :norm, type: Integer
  field :finished_at, type: DateTime
  field :event_string, type: String
  belongs_to :website
  belongs_to :user

  taggable_on :main_types
  taggable_on :categories
  taggable_on :countries
  taggable_on :types
  taggable_on :brands

  searchable do
    text :name
    string :countries, multiple: true
    string :main_types, multiple: true
    string :types, multiple: true
    string :brands, multiple: true
    float :current_price
    float :min_price
    time :updated_at
  end

  has_many :wine_prices
  has_and_belongs_to_many :wines
  has_many :comments, as: :commentable
  has_many :user_monitors
  has_many :wine_links

  scope :recent, desc(:updated_at)
  scope :cheapest, asc(:current_price)
  scope :running, where(:finished_at => nil)
  scope :finished, where(:finished_at.nin => [nil])
  scope :cheapest_per_liter, asc(:price_per_liter)
  default_scope where(:name.nin => [nil,''], :current_price.nin => [nil])

  #validates :wines, presence: true
  validates :sn, presence: true, uniqueness: { :scope => :website }

  after_update :set_price_per_liter, :set_wine_price, :monitoring_remind
  after_create :set_price_per_liter, :set_lib, :init_from_page, :get_price, :refilter

  index({ name: 1 }, { background: true })
  index({ current_price: 1 }, { background: true })
  index({ min_price: 1 }, { background: true })
  index({ updated_at: -1 }, { background: true })

  def to_s
    name
  end

  def monitoring_remind
    user_monitors.where(:warn_price.gte => current_price).each do |user_monitor|
      UserMailer.user_monitor(user_monitor).deliver
    end if current_price and current_price > 0
  end

  def set_wine_price
    wines.each do |wine|
      if min_price.nil? or min_price == 0 or (current_price < min_price)
        update_attribute :min_price, current_price
      end

      if wine.min_price.nil? or wine.min_price == 0 or (current_price < wine.min_price)
        wine.update_attribute :min_price, current_price
      end

      the_cheapest = wine.wine_monitors.cheapest.first
      wine.update_attributes current_price: the_cheapest.try(:current_price), event_string: the_cheapest.try(:event_string)
    end if current_price
  end

  def url
    @url ||= lib.constantize.new(id: sn).url
  end

  def finish
    update_attribute :finished_at, Time.now if finished_at.nil?
  end

  def restart
    update_attribute :finished_at, nil unless finished_at.nil?
  end

  def set_price_per_liter
    if norm and norm > 0
      tmp_price_per_liter = (current_price / (norm.to_f / 1000)).to_money

      update_attribute :price_per_liter, tmp_price_per_liter if tmp_price_per_liter != price_per_liter
      update_attribute :min_price_per_liter, tmp_price_per_liter if min_price_per_liter.nil? or tmp_price_per_liter < min_price_per_liter
      set_wine_price_per_liter
    end if current_price
  end

  def set_wine_price_per_liter
    wines.each do |wine|
      if wine.min_price_per_liter.nil? or wine.min_price_per_liter == 0 or min_price_per_liter < wine.min_price_per_liter
        wine.update_attribute :min_price_per_liter, min_price_per_liter
      end
      wine.update_attribute :price_per_liter, wine.wine_monitors.cheapest_per_liter.first.try(:price_per_liter)
    end if min_price_per_liter
  end

  def set_lib
    update_attribute :lib, website.lib if website
  end

  def init_from_page
    (lib + "Crawler").constantize.new.init_from_page(self)
  end

  def get_price
    (lib + "Crawler").constantize.new.get(self)
  end

  def refilter
    WineFilterController.new.refilter_wine_monitor self
  end

  def self.categories
    all.map(&:categories).flatten.uniq
  end

  def self.category(category_name)
    WineMonitor.tagged_with_on(:categories, category_name)
  end

  def self.full_search q, page = 1, plus = {}
    q ||= ''
    q = q.gsub('"', '"\\')
    s = WineMonitor.search do
      fulltext q do
        boost_fields :name => 3.0
      end
      ['main_type', 'type', 'country', 'brand'].each do |str|
        with (str+'s'), plus[str] unless plus[str].blank?
      end
      if plus[:sort] and @match_sort = plus[:sort].match(/(.*)_(asc|desc)/)
        order_by @match_sort[1].to_sym, @match_sort[2].to_sym if ['current_price', 'min_price'].include?(@match_sort[1])
        #order_by :updated_at, :desc
      end
      paginate per_page: 20, page: page
    end
  end
end

app/controllers/wine_monitors_controller.rb
class WineMonitorsController < InheritedResources::Base
  before_filter :authenticate_user!,only: [:new,:create]
  actions :index, :show, :new, :create
  layout 'sidebar', only: :show

  def index
    index! do
      ['main_type', 'type', 'country', 'brand'].each do |sym|
        @wine_monitors = @wine_monitors.tagged_with_on(sym.tableize.to_sym, params[sym]) unless params[sym].blank?
      end
    end
  end

  def show
    show! do
      add_crumb(I18n.t("controller.wine_monitors"), wine_monitors_path)
      add_crumb(@wine_monitor, wine_path(@wine_monitor))
    end
  end

  def links
    if YAML.load(ENV['CRAWLS']).include?(params[:lib])
      redirect_to params[:lib].constantize.new({id: params[:id]}).go_url
    end
  end

  def categories
    @categories = WineMonitor.categories
  end

  def category
    @category = params[:id]
    unless params[:sort].blank?
      @wine_monitors ||= WineMonitor.category(params[:id]).sorted(params[:sort] || '').page(params[:page])
    else
      @wine_monitors ||= WineMonitor.category(params[:id]).recent.page(params[:page])
    end
    add_crumb(I18n.t("controller.wine_monitors"), wine_monitors_path)
    add_crumb('分类', categories_wine_monitors_path)
    add_crumb(@category, category_wine_monitors_path(@category))
    render :index
  end

  def search
    if params[:q].blank?
      redirect_to wine_monitors_path
    else
    s = WineMonitor.full_search(params[:q], params[:page], params)
    @keys = params[:q].blank? ? [] : params[:q].split(' ').uniq
    @wine_monitors = s.results
    add_crumb(I18n.t("controller.wine_monitors"), wine_monitors_path)
    add_crumb('搜索')#, categories_wine_monitors_path)
    end
    #respond_to do |f|
      #f.json{render json: {results: @wine_monitor, has_next: !@wine_monitor.last_page?}}
      #f.html
    #end
  end


  protected
  def collection
    add_crumb(I18n.t("controller.wine_monitors"), wine_monitors_path)
    unless params[:sort].blank?
      @wine_monitors ||= end_of_association_chain.sorted(params[:sort] || '').page(params[:page])
    else
      @wine_monitors ||= end_of_association_chain.recent.page(params[:page])
    end
  end

end

app/views/wine_monitors/_form.html.erb
<%= simple_form_for(@wine_monitor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :website, collection: Website.all, include_blank: nil %>
    <%= f.input :sn, hint: '如京东在商品介绍中：“商品编号：1028917089”' %>
    <%= f.input :norm, hint: '输入正确的规格（即多少ML，只填写数字），可以更好的反馈均价信息给您。' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/wine_monitors/_trs.html.erb
<% @wine_monitors.each do |wine_monitor| %>
  <tr>
    <td><%= link_to wine_monitor.name.try(:html_safe), wine_monitor,target: '_blank', title: wine_monitor.name.try(:html_safe) %></td>
    <td><%= wine_monitor.current_price %></td>
    <td><%= wine_monitor.min_price %></td>
    <td><%= wine_monitor.event_string.try(:block,20) %></td>
    <td><%= wine_monitor.updated_at.cc_time %></td>
    <td>
      <%= link_to '直接访问', go_path(id: wine_monitor.sn, lib: wine_monitor.lib), class: 'btn btn-primary', target: '_blank', rel: 'external nofollow' %>
    </td>
  </tr>
<% end -%>

app/views/wine_monitors/_wine_monitor.html.erb
<ul class="inline">
  <li><%= link_to wine_monitor.name.try(:html_safe), wine_monitor,target: '_blank', title: wine_monitor.name.try(:html_safe) %></li>
  <li><%= wine_monitor.norm %></li>
  <li><%= wine_monitor.current_price %></li>
  <li><%= wine_monitor.min_price %></li>
</ul>

app/views/wine_monitors/categories.html.erb
<h1><%= title '商品分类' %></h1>
<ul class="inline">
  <% @categories.each do |category| %>
    <li><%= link_to category, category_wine_monitors_path(category) %>(<%= WineMonitor.tagged_with_on(:categories, category).count %>)</li>
  <% end -%>
</ul>

app/views/wine_monitors/index.html.erb
<h1>酒监视器列表</h1>
<div class="tabbable">
  <%#= render_cell :wine_monitors, :categories, category: @category, class: WineMonitor %>
  <%= render_cell :wine_monitors, :tags, args: params %>
  <table class="table table-striped table-hover sortable">
    <%= render_cell :wine_monitors, :thead, args: params %>
    <tbody>
      <%= render 'wine_monitors/trs' %>
    </tbody>
  </table>
  <div class="pull-right">
    <%= paginate @wine_monitors %>
  </div>
</div>
<%#<script type="text/javascript">%>
  <%#$('th.sort').click(function(){%>
    <%#if($(this).children('.reversed.up').length > 0 || $(this).children('.reversed').length == 0){%>
      <%#window.location.href="?sort=" + $(this).data('column') + '_asc';%>
    <%#}%>
    <%#else{%>
      <%#window.location.href = "?sort=" + $(this).data('column') + '_desc';%>
    <%#}%>
  <%#})%>
<%#</script>%>

app/views/wine_monitors/new.html.erb
<h1><%= title '新建酒价监视器' %></h1>

<%= render 'form' %>

<%= link_to 'Back', wine_monitors_path %>

app/views/wine_monitors/search.html.erb
<h1>搜索 <%= params[:q] %> 第<%= params[:page] || 1 %>页</h1>
<div class="tabbable">
  <%= render_cell :wine_monitors, :tags, args: params %>
  <table class="table table-striped table-hover sortable">
    <%= render_cell :wine_monitors, :thead, args: params %>
    <tbody>
      <% @wine_monitors.each do |wine_monitor| %>
        <tr>
          <td><%= link_to highlight(wine_monitor.name.try(:html_safe), @keys), wine_monitor,target: '_blank', title: wine_monitor.name.try(:html_safe) %></td>
          <td><%= wine_monitor.current_price %></td>
          <td><%= wine_monitor.min_price %></td>
          <td><%= wine_monitor.event_string.try(:block,30) %></td>
          <td><%= wine_monitor.updated_at.cc_time %></td>
          <td>
            <%= link_to '直接访问', go_path(id: wine_monitor.sn, lib: wine_monitor.lib), class: 'btn btn-primary', target: '_blank', rel: 'external nofollow' %>
          </td>
        </tr>
      <% end -%>
    </tbody>
  </table>
  <div class="pull-right">
    <%= paginate @wine_monitors %>
  </div>
</div>
<%#<script type="text/javascript">%>
  <%#$('th.sort').click(function(){%>
    <%#if($(this).children('.reversed.up').length > 0 || $(this).children('.reversed').length == 0){%>
      <%#window.location.href="?sort=" + $(this).data('column') + '_asc';%>
    <%#}%>
    <%#else{%>
      <%#window.location.href = "?sort=" + $(this).data('column') + '_desc';%>
    <%#}%>
  <%#})%>
<%#</script>%>

app/views/wine_monitors/show.html.erb
<h1><%= title @wine_monitor.name.try(:html_safe) %></h1>
<h3>价格信息</h3>

<%= content_tag :dl,class: 'dl-horizontal' do %>
  <%= d @wine_monitor, :current_price, ' 元' %>
  <%= d @wine_monitor, :fit_price, ' 元' %>
  <%= d @wine_monitor, :min_price, ' 元' %>
  <% if @wine_monitor.norm and @wine_monitor.norm > 0 %>
    <%= d @wine_monitor, :norm, ' mL' %>
    <%= d @wine_monitor, :price_per_liter, ' 元/L' %>
    <%= d @wine_monitor, :min_price_per_liter, ' 元/L' %>
  <% end -%>
  <%= d @wine_monitor, :event_string %>
  <dt>分类</dt>
  <dd>
  <ul class="inline">
    <% @wine_monitor.categories.each do |category| %>
      <li><%= link_to category, category_wine_monitors_path(category), target: '_blank' %></li>
    <% end -%>
  </ul>
  </dd>
  <dt>&nbsp;</dt>
  <dd>
  <p>
    <%= link_to '访问', go_path(id: @wine_monitor.sn, lib: @wine_monitor.lib), class: 'btn btn-primary', target: '_blank', rel: 'external nofollow' %>
  </p>
  <p>
    <% if current_user %>
      <%= button_to '设置监视器', new_user_monitor_path(wine_monitor_id: @wine_monitor), method: :get, remote: true, class: 'btn btn-primary' %>
    <% else %>
      <%= render "application/login", warn: '监视酒价、设置邮件提醒' %>
    <% end %>
  </p>
  </dd>
<% end -%>

<% unless @wine_monitor.description.blank? %>
  <h3>详细介绍</h3>
  <div class="well">
    <%= @wine_monitor.description.try(:html_safe) %>
  </div>
<% end -%>

<% if @wine_monitor.wine_prices.any? %>
  <h3>历史价格</h3>
  <ul class="unstyled bb mb10">
    <% @wine_monitor.wine_prices.recent.each do |wine_price| %>
      <li><%= link_to "#{wine_price.current_price}/#{wine_price.tag_price}", go_path(id: @wine_monitor.sn, lib: @wine_monitor.lib), target: '_blank', rel: 'external nofollow' %>(<%= '%1.1f' % (10 * wine_price.current_price.to_f / wine_price.tag_price.to_f) %>折)<div class="pull-right">(开始于<%= wine_price.started_at %><%= wine_price.finished_at ? ",截止于#{wine_price.finished_at}" : "至今" %>)</div></li>
    <% end -%>
  </ul>
  <div class="clearfix"></div>
<% end -%>

<%= render "comments/all", parent: @wine_monitor %>

<script type="text/javascript">
  $('#wine_prices_history a').click(function (e) {
    e.preventDefault();
    $(this).tab('show');
  })
</script>