config/routes.rb
WineCrawl::Application.routes.draw do
  match '/search' => 'wine_monitors#search'#, defaults: {page: 1}
  authenticated :user do
    root :to => 'wine_monitors#index'
    scope module: 'user' do
      resources :wine_links
    end
  end
  resources :wine_links
  resources :user_monitors
  resources :comments, only: [:index, :show, :create]
  get '/go/:lib/:id' => 'wine_monitors#links',as: :go
  post '/go/:lib/:id' => 'wine_monitors#links',as: :go
  resources :wine_monitors, only: [:index, :show, :new, :create] do
    resources :comments, only: [:index,:create]
    get 'category/:id' => 'wine_monitors#category', on: :collection, as: 'category'
    get 'categories' => 'wine_monitors#categories', on: :collection, as: 'categories'
    #collection do
      #match :search
    #end
  end
  resources :wines, only: [:index, :show] do
    resources :comments, only: [:index,:create]
  end
  #resources :wine_price_histories
  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "wine_monitors#index"

  devise_for :users, controllers: {
    omniauth_callbacks: :authentications,
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  ActiveAdmin.routes(self)
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><%= title %></h4>
      </div>
      <div class="modal-body">
        <p><%= body %></p>
      </div>
      <%#<div class="modal-footer">%>
        <%#<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>%>
        <%#<button type="button" class="btn btn-primary">Save changes</button>%>
      <%#</div>%>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>

<%= link_to t('site_title'), root_url(subdomain: ENV['SUBDOMAIN']), :class => 'brand' %>
<div class="nav-collapse collapse">
  <ul class="nav navbar-nav">
    <li>
      <%= link_to '选酒中心', wines_url %>
    </li>
    <li>
      <%= link_to '美酒价格', wine_monitors_url %>
    </li>
    <li>
      <%= link_to '酒价监视', new_wine_link_url %>
    </li>
    <form class="navbar-search pull-left" role="search" action="/search">
      <input type="text" class="form-control" placeholder="搜索..." name="q">
    </form>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <%= render_cell :layouts, :login, user: current_user %>
  </ul>
</div>

app/views/layouts/application.html.erb
<%= render 'application/before_layout' %>
<div class="container">
  <div class="row">
    <div class="span12">
      <% unless controller_name == 'home' %>
        <div class="breadcrumb">
          <%= render_crumbs separator: ' > ' %>
        </div>

      <% end %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
</div> <!--! end of .container -->
<div id="footer">
  <div class="footer-container">
    <ul class="inline">
      <%#<li><a href="http://weibo.com/u/2865390333" target="_blank" rel="nofollow">新浪微博：@神马价</a></li>%>
    </ul>
    <p id="copyright">© 2013 DestinyD(destinyd_ror<%= image_tag 'at.gif' %>163.com)</p>
  </div>
</div>
</body>
</html>

app/views/layouts/sidebar.html.erb
<%= render 'application/before_layout' %>
<div class="container">
  <div class="row">
    <div class="span12">

      <%= render 'layouts/messages' %>

      <div class="row-fluid">
        <div class="span8">
          <% unless controller_name == 'home' %>
            <div class="breadcrumb">
              <%= render_crumbs separator: ' > ' %>
            </div>

          <% end %>
          <%= yield %>
        </div>
      </div>
      <div class="span4">
        <%= yield(:sidebar) %>
      </div>
    </div>
  </div> <!--! end of .container -->
  <div id="footer">
    <div class="footer-container">
      <ul class="inline">
        <%#<li><a href="http://weibo.com/u/2865390333" target="_blank" rel="nofollow">新浪微博：@神马价</a></li>%>
      </ul>
      <p id="copyright">© 2013 DestinyD(destinyd_ror<%= image_tag 'at.gif' %>163.com)</p>
    </div>
  </div>
</body>
</html>